### PR TITLE
Zoom refactoring

### PR DESCRIPTION
**Pull request by M4anuel**
extracted zooming for easier modification of zoom function and cleaner code in the dicomimagerenderer

### CODE REVIEW

**Comment by michael-duer** [comment]
The code looks good but there seems to be a bug that if you zoom too fast(?) it will lead to a wrong value for the zoom level.

All of these three images show a zoom level of 200%:
image
image
image

**Comment by laurabuenemann** [comment]
Could utils_zoom.js be renamed to zoomUtils.js or is this not the convention? I named the other util files valueUtils.js etc and it would be nice if the names were consistent

**Comment by M4anuel** [comment]
> bug that if you zoom too fast(?) it will lead to a wrong value for the zoom level.
> 
> All of these three images show a zoom level of 200%:

I can't seem to replicate that bug, do you have some instructions for me?
Here's how 200% looks for me:
image

**Comment by M4anuel** [comment]
> Could utils_zoom.js be renamed to zoomUtils.js or is this not the convention? I named the other util files valueUtils.js etc and it would be nice if the names were consistent

I namend my files after utils_point_projection and utils_plane, but we can change that, I don't mind

**Pull request merged**
